import type { Lang } from './types.ts';
const words = {
  title: ['QR Scanner', 'QR Scanner'],
  description: [
    'Đọc QR từ ảnh hoặc camera. Dán ảnh bằng Ctrl + V, chọn file hoặc nhập link ảnh. Xử lý ngay trong trình duyệt.',
    'Read QR codes from images or your camera. Paste with Ctrl + V, choose a file or enter an image link. Decode in your browser.',
  ],
  tagline: [
    'Dán ảnh. Đọc mã. Xem đầy đủ nội dung.',
    'Paste an image. Read the code. See the whole message.',
  ],
  intro: [
    'Dán ảnh bằng Ctrl + V hoặc Cmd + V, kéo ảnh vào đây hoặc chọn ảnh. Không cần tài khoản.',
    'Paste an image with Ctrl + V or Cmd + V, drop it here or choose a file. No account needed.',
  ],
  inputTitle: ['Ảnh của bạn', 'Your image'],
  dropTitle: ['Dán hoặc kéo thả ảnh QR', 'Paste or drop a QR image'],
  pastePlaceholder: ['Ctrl + V hoặc Dán', 'Ctrl + V or Paste'],
  cameraAction: ['Camera', 'Camera'],
  imageHelpTitle: ['Cách nhập ảnh QR', 'How to import a QR image'],
  dropHelp: [
    'PNG, JPEG, WebP, GIF, BMP hoặc AVIF. Tối đa 20 MB. GIF được đọc ở khung đầu tiên.',
    'PNG, JPEG, WebP, GIF, BMP or AVIF. Up to 20 MB. GIF uses the first frame.',
  ],
  choose: ['Chọn ảnh', 'Choose image'],
  paste: ['Dán ảnh', 'Paste image'],
  pasteHelp: [
    'Chọn vùng dán rồi nhấn Ctrl+V hoặc Cmd+V. Trên điện thoại, dùng Dán trên bàn phím. Nếu nút Dán ảnh không dùng được, hãy dùng bàn phím hoặc chọn ảnh.',
    'Select the paste area and press Ctrl+V or Cmd+V. On a phone, use Paste on your keyboard. If the Paste image button is unavailable, use your keyboard or choose an image.',
  ],
  urlTitle: ['Dùng link ảnh', 'Use an image link'],
  urlPlaceholder: ['https://example.com/qr.png', 'https://example.com/qr.png'],
  urlHelp: [
    'Bấm Quét sẽ tải ảnh từ website chứa ảnh.',
    'Scan downloads the image from its website.',
  ],
  scanURL: ['Quét', 'Scan'],
  switchCamera: ['Đổi camera', 'Switch camera'],
  cancelCamera: ['Hủy', 'Cancel'],
  cameraRequest: ['Đang chờ quyền dùng camera.', 'Waiting for camera access.'],
  cameraHelp: [
    'Bấm Camera rồi cho phép dùng máy ảnh. Đưa QR vào khung và giữ máy ổn định. Camera tự dừng khi đọc được mã.',
    'The camera starts only when you ask. Keep the QR code in view and hold steady. It stops after a successful scan.',
  ],
  stop: ['Dừng camera', 'Stop camera'],
  cameraActual: ['Camera đang dùng', 'Active camera'],
  videoLabel: [
    'Hình ảnh camera để quét QR',
    'Camera view for scanning QR codes',
  ],
  clear: ['Xóa ảnh và kết quả', 'Clear image and results'],
  privacy: [
    'Ảnh và nội dung QR được xử lý trên thiết bị. Không gửi tới dịch vụ giải mã, không lưu lịch sử.',
    'Images and QR contents are processed on your device. No decoding service and no saved history.',
  ],
  resultTitle: ['Nội dung QR', 'QR contents'],
  empty: [
    'Kết quả sẽ hiện ở đây khi bạn dán ảnh, chọn ảnh hoặc bật camera.',
    'Your result appears here after you paste an image, choose a file or start the camera.',
  ],
  scanning: ['Đang đọc ảnh', 'Reading the image'],
  watching: [
    'Đang tìm QR trong khung hình',
    'Looking for a QR code in the camera view',
  ],
  success: ['Đã đọc được QR', 'QR code read'],
  codeFound: ['mã được tìm thấy', 'code found'],
  codes: ['mã được tìm thấy', 'codes found'],
  previewAlt: ['Ảnh đang được quét', 'Image being scanned'],
  copy: ['Sao chép nội dung', 'Copy contents'],
  download: ['Tải nội dung', 'Download contents'],
  downloadJSON: ['Tải toàn bộ kết quả', 'Download all results'],
  copied: ['Đã sao chép nội dung.', 'Contents copied.'],
  copyFallback: [
    'Trình duyệt chưa cho phép sao chép. Chọn nội dung bên dưới rồi dùng Ctrl + C hoặc Cmd + C.',
    'Copy access is unavailable. Select the text below and press Ctrl + C or Cmd + C.',
  ],
  openLink: ['Mở link này', 'Open this link'],
  linkWarning: [
    'Chỉ mở nếu bạn tin nguồn QR. Trang này không kiểm tra độ an toàn của link.',
    'Open only if you trust the QR source. This page does not check whether a link is safe.',
  ],
  unsafeLink: [
    'Nội dung này có lệnh hoặc loại link không được mở từ công cụ. Bạn vẫn có thể xem và sao chép nguyên văn.',
    'This contains a command or a link type this tool does not open. You can still read and copy the original text.',
  ],
  raw: ['Nội dung nguyên văn', 'Original contents'],
  sensitive: [
    'Thông tin riêng tư trong QR',
    'Private information in this QR code',
  ],
  sensitiveHelp: [
    'QR này có thể chứa mật khẩu hoặc khóa xác thực. Chỉ mở phần này khi không có người khác nhìn màn hình.',
    'This QR code may contain a password or authentication key. Reveal it only when others cannot see your screen.',
  ],
  technical: ['Thông tin kỹ thuật', 'Technical details'],
  technicalHelp: [
    'Đây là thông tin bộ giải mã đọc được. Thông tin không có trong QR hoặc không được bộ giải mã cung cấp sẽ được ghi rõ.',
    'These are the details reported by the decoder. Missing or unsupported information is marked clearly.',
  ],
  unknown: ['Không được cung cấp', 'Not reported'],
  variant: ['Dạng QR', 'QR format'],
  version: ['Phiên bản QR', 'QR version'],
  grid: ['Kích thước lưới', 'Module grid'],
  correction: ['Mức sửa lỗi', 'Error correction'],
  mask: ['Mẫu mặt nạ', 'Mask pattern'],
  rotation: ['Góc xoay', 'Rotation'],
  mirror: ['Ảnh bị lật', 'Mirrored'],
  inverted: ['Màu đảo ngược', 'Inverted'],
  encoding: ['Dữ liệu ký tự', 'Character data'],
  identifier: ['Mã nhận diện', 'Symbology identifier'],
  append: ['Chuỗi QR ghép', 'Structured append'],
  position: ['Vị trí trong ảnh', 'Position in the image'],
  pixels: ['Ảnh đã xử lý', 'Processed image'],
  duration: ['Thời gian giải mã', 'Decode time'],
  decoder: ['Bộ giải mã', 'Decoder'],
  bytes: ['Dữ liệu gốc dạng hex', 'Original bytes in hex'],
  bytesECI: ['Dữ liệu theo ECI dạng hex', 'ECI bytes in hex'],
  metadata: ['Thông tin bổ sung nguyên văn', 'Original extra metadata'],
  yes: ['Có', 'Yes'],
  no: ['Không', 'No'],
  plain: ['Văn bản', 'Text'],
  link: ['Link', 'Link'],
  wifi: ['Wi-Fi', 'Wi-Fi'],
  email: ['Email', 'Email'],
  phone: ['Số điện thoại', 'Phone number'],
  sms: ['Tin nhắn', 'Text message'],
  contact: ['Danh bạ', 'Contact'],
  location: ['Vị trí', 'Location'],
  calendar: ['Lịch', 'Calendar event'],
  auth: ['Khóa xác thực', 'Authentication key'],
  network: ['Tên mạng', 'Network name'],
  security: ['Kiểu bảo mật', 'Security type'],
  password: ['Mật khẩu', 'Password'],
  hiddenNetwork: ['Mạng ẩn', 'Hidden network'],
  address: ['Địa chỉ', 'Address'],
  subject: ['Tiêu đề', 'Subject'],
  message: ['Nội dung', 'Message'],
  name: ['Tên', 'Name'],
  organization: ['Tổ chức', 'Organization'],
  latitude: ['Vĩ độ', 'Latitude'],
  longitude: ['Kinh độ', 'Longitude'],
  issuer: ['Dịch vụ', 'Issuer'],
  account: ['Tài khoản', 'Account'],
  secret: ['Khóa bí mật', 'Secret key'],
  algorithm: ['Thuật toán', 'Algorithm'],
  digits: ['Số chữ số', 'Digits'],
  period: ['Chu kỳ', 'Period'],
  counter: ['Bộ đếm', 'Counter'],
  starts: ['Bắt đầu', 'Starts'],
  ends: ['Kết thúc', 'Ends'],
  fileType: [
    'Chọn ảnh PNG, JPEG, WebP, GIF, BMP hoặc AVIF. File này không phải ảnh được hỗ trợ.',
    'Choose a PNG, JPEG, WebP, GIF, BMP or AVIF image. This file is not a supported image.',
  ],
  fileSize: [
    'Ảnh lớn hơn 20 MB. Hãy dùng ảnh nhỏ hơn hoặc chụp riêng vùng QR.',
    'The image exceeds 20 MB. Use a smaller image or crop to the QR code.',
  ],
  imageSize: [
    'Ảnh quá lớn để xử lý an toàn. Dùng ảnh dưới 24 triệu điểm ảnh và mỗi cạnh không quá 12.000 điểm ảnh.',
    'The image is too large to process safely. Use fewer than 24 million pixels and no side above 12,000 pixels.',
  ],
  imageUnreadable: [
    'Không đọc được file ảnh. Hãy thử ảnh khác hoặc chụp màn hình phần QR.',
    'The image could not be opened. Try another image or a screenshot of the QR code.',
  ],
  noQR: [
    'Chưa tìm thấy QR. Hãy dùng ảnh rõ hơn, giữ đủ phần viền quanh mã hoặc cắt bớt vùng thừa.',
    'No QR code was found. Try a sharper image, keep the border around the code or crop away extra space.',
  ],
  timeout: [
    'Ảnh mất quá nhiều thời gian để đọc. Hãy thử ảnh nhỏ hơn hoặc cắt riêng vùng QR.',
    'Reading took too long. Try a smaller image or crop to the QR code.',
  ],
  decoderFailed: [
    'Không tải được bộ đọc QR. Kiểm tra kết nối rồi thử lại. Ảnh chưa được gửi đi.',
    'The QR reader could not load. Check your connection and try again. Your image was not sent anywhere.',
  ],
  invalidURL: [
    'Nhập link đầy đủ bắt đầu bằng https hoặc http và không chứa tài khoản đăng nhập.',
    'Enter a complete https or http image link without login credentials.',
  ],
  urlBlocked: [
    'Không tải được ảnh. Link có thể hỏng hoặc máy chủ chặn việc đọc ảnh. Hãy tải ảnh về rồi dán hoặc chọn file.',
    'The image could not be fetched. The link may be broken or its server may block access. Download the image, then paste it or choose the file.',
  ],
  clipboardDenied: [
    'Trình duyệt chưa cho phép đọc ảnh đã sao chép. Hãy dùng Ctrl + V hoặc Cmd + V, hoặc chọn file ảnh.',
    'Your browser could not read the copied image. Press Ctrl + V or Cmd + V, or choose an image file.',
  ],
  clipboardEmpty: [
    'Chưa có ảnh trong nội dung đã sao chép. Hãy sao chép ảnh hoặc chụp màn hình QR trước.',
    'No image was found in your clipboard. Copy an image or take a QR screenshot first.',
  ],
  cameraDenied: [
    'Quyền camera chưa được cho phép. Bạn có thể cho phép trong trình duyệt hoặc dùng ảnh QR.',
    'Camera access was not allowed. You can allow it in your browser or use a QR image instead.',
  ],
  cameraMissing: [
    'Không tìm thấy camera phù hợp. Thử đổi camera hoặc dùng ảnh QR.',
    'No suitable camera was found. Try another camera preference or use a QR image.',
  ],
  cameraFailed: [
    'Không mở được camera. Kiểm tra camera có đang được ứng dụng khác dùng hay không.',
    'The camera could not start. Check whether another application is using it.',
  ],
  cameraUnavailable: [
    'Trình duyệt này không dùng được camera ở đây. Hãy mở trang bằng HTTPS hoặc dùng ảnh QR.',
    'This browser cannot use a camera here. Open the HTTPS page or use a QR image.',
  ],
  stopped: ['Camera đã dừng.', 'Camera stopped.'],
  cleared: ['Đã xóa ảnh và kết quả.', 'Image and results cleared.'],
  noScript: [
    'Bật JavaScript để đọc QR trên thiết bị. Trang không gửi ảnh tới máy chủ để xử lý thay.',
    'Enable JavaScript to read QR codes on your device. This page does not send images to a server for decoding.',
  ],
  faqTitle: ['Điều bạn cần biết', 'What to know'],
  faq1: [
    'Ảnh và nội dung QR có được gửi đi không?',
    'Are images or QR contents sent anywhere?',
  ],
  answer1: [
    'Ảnh bạn dán, chọn hoặc chụp bằng camera được giải mã ngay trên thiết bị. Không lưu lịch sử. Với link ảnh, trình duyệt tải ảnh trực tiếp từ địa chỉ bạn nhập khi bạn yêu cầu quét. Máy chủ ảnh có thể ghi nhận lần tải đó.',
    'Pasted images, selected files and camera frames are decoded on your device. No history is saved. For an image link, your browser fetches the image directly from that address when you ask to scan it. Its server may log that request.',
  ],
  faq2: [
    'Vì sao link ảnh có thể không quét được?',
    'Why can an image link fail?',
  ],
  answer2: [
    'Link cần dẫn tới file ảnh và máy chủ cần cho phép trình duyệt đọc ảnh từ website khác. Nếu bị chặn, tải ảnh về rồi dán hoặc chọn file. Công cụ không dùng máy chủ trung gian để vượt hạn chế này.',
    'The link needs to return an image, and its server must allow reading from another website. If access is blocked, download the image and paste it or choose the file. This tool does not use a proxy to bypass that restriction.',
  ],
  faq3: ['Công cụ đọc được những QR nào?', 'Which QR codes can it read?'],
  answer3: [
    'Bộ đọc hỗ trợ QR thông thường, Micro QR và QR chữ nhật. Một ảnh có thể cho nhiều kết quả, tối đa 16 mã. Mã quá mờ, bị che hoặc không đủ viền có thể không đọc được.',
    'The reader supports ordinary QR codes, Micro QR and rectangular QR codes. One image can return up to 16 results. Blurred, covered or tightly cropped codes may not decode.',
  ],
  faq4: [
    'Thông tin kỹ thuật có ý nghĩa gì?',
    'What do the technical details mean?',
  ],
  answer4: [
    'Phiên bản và kích thước lưới cho biết cấu trúc mã. Mức sửa lỗi mô tả phần dữ liệu dự phòng để phục hồi khi mã hư hại. Góc xoay, vị trí, dữ liệu gốc và thông tin bộ giải mã cũng có thể được xem trong kết quả. Các con số này không xác nhận link an toàn.',
    'The version and module grid describe the code structure. Error correction describes redundant data that helps recover a damaged code. Results also show orientation, position, original bytes and decoder information when available. These details do not certify a safe link.',
  ],
  generatorTitle: ['Cần tạo QR?', 'Need to make a QR code?'],
  generatorCopy: [
    'Dùng QR Generator để tạo mã cho link, văn bản, Wi-Fi hoặc danh bạ. Nội dung được giữ nguyên trong mã.',
    'Use QR Generator for links, text, Wi-Fi or contact details. Your contents stay in the code.',
  ],
  generatorLink: ['Mở QR Generator', 'Open QR Generator'],
  source: ['Mã nguồn', 'Source code'],
  licenses: ['Giấy phép và ghi nhận', 'Licenses and notices'],
  home: ['Trang chủ VINASIG', 'VINASIG home'],
  skip: ['Đến công cụ', 'Skip to scanner'],
  references: ['Tài liệu của ZXing', 'ZXing documentation'],
} as const;
export type CopyKey = keyof typeof words;
export function copy(lang: Lang): Record<CopyKey, string> {
  return Object.fromEntries(
    Object.entries(words).map(([key, pair]) => [
      key,
      pair[lang === 'vi' ? 0 : 1],
    ]),
  ) as Record<CopyKey, string>;
}
